language: nix

sudo: true

git:
  depth: 1

env:
  global:
  matrix:
    - GHCVERSION=ghc802
    - GHCVERSION=ghc822
    - GHCVERSION=ghc843
    - GHCVERSION=ghc865
    - GHCVERSION=ghc884

matrix:
  allow_failures:
  exclude:

script:
  - (cd gitlib ; nix-build --argstr compiler $GHCVERSION)

# branches:
#   only:
#     - master
